language: java
jdk:
- oraclejdk8
sudo: false
script: mvn clean package
after_success:
  - echo "Smoke deployment initiated..."
  - curl --upload-file 'target/NC_4_2017_1.war' "http://$NC_SERVER:$TOMCAT_PORT/manager/text/deploy?path=/dev&update=true" --user $TOMCAT_CREDENTIALS
  - if [ -n "$TRAVIS_TAG" ]; then echo "Production deployment initiated..."; fi
  - if [ -n "$TRAVIS_TAG" ]; then curl --upload-file 'target/NC_4_2017_1.war' "http://$NC_SERVER:$TOMCAT_PORT/manager/text/deploy?path=/production&update=true" --user $TOMCAT_CREDENTIALS; fi
notifications:
  email:
    recipients:
      - mishkinstvo@outlook.com
      - viktor.mazepa@netcracker.com
      - boris.katran@gmail.com
      - Ververo3@gmail.com
      - veniqs@gmail.com
      - seraphicps@gmail.com
      - creshibon@gmail.com
      - OHorsunenko@gmail.com
      - andrii.latyshev@NetCracker.com
    on_success: always
    on_failure: always
